"""empty message

Revision ID: d5820c8cb044
Revises: 
Create Date: 2020-11-21 11:16:08.512233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5820c8cb044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'word', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_column('word', 'user_id')
    # ### end Alembic commands ###
